"""
Pydantic v2 schemas for SyndicateBrain.

Law 1: Evidence is immutable.
Law 3: Every edge carries provenance.

CRITICAL: Edge MUST carry source_doc_id: str and locator: str as required
fields with NO default and NO Optional. An edge without provenance must be
impossible to construct.
"""

from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field


class Doc(BaseModel):
    """Represents an ingested evidentiary document in 01_Evidence_Inbox/."""
    model_config = ConfigDict(extra="allow")

    id: str
    path: str
    kind: str  # FIR | CDR | TowerDump | Statement | FieldLog | Misc
    sha256: str
    bytes: int
    ingested_at: str
    ingested_by: str
    page_count: Optional[int] = None


class Provenance(BaseModel):
    """
    Provenance record for an edge or claim.
    Points to a verified source document and exact locator.
    """
    model_config = ConfigDict(extra="allow")

    source_doc_id: str
    locator: str  # e.g. 'page:3 line:11' or 'row:4182'
    observed_at: Optional[str] = None
    weight: float = 1.0
    tier: str = "deterministic"  # 'deterministic' | 'hypothesis'
    snippet: Optional[str] = None
    cypher: Optional[str] = None
    sql: Optional[str] = None
    derivation_chain: Optional[str] = None
    doc: Optional[Doc] = None


class Edge(BaseModel):
    """
    Graph relationship between two entities.

    NON-NEGOTIABLE CONSTRAINT:
    Edge MUST carry source_doc_id: str and locator: str with NO default
    and NO Optional. A provenance-less edge is unrepresentable.
    """
    model_config = ConfigDict(extra="allow")

    id: str
    source: str
    target: str
    type: str  # CALLED | SMS_TO | USES_PHONE | USES_DEVICE | PINGED | NAMED_IN | CO_ACCUSED | OWNS_VEHICLE | PRESENT_AT | MEMBER_OF | MENTIONS
    source_doc_id: str
    locator: str
    observed_at: Optional[str] = None
    weight: float = 1.0
    tier: str = "deterministic"
    properties: dict[str, Any] = Field(default_factory=dict)


class Node(BaseModel):
    """Entity node in the knowledge graph."""
    model_config = ConfigDict(extra="allow")

    id: str
    type: str  # Person | Phone | Device | Vehicle | Tower | Location | Org | FIR | Event | Doc
    label: str
    canonical_name: Optional[str] = None
    aliases: list[str] = Field(default_factory=list)
    thana: Optional[str] = None
    first_seen: Optional[str] = None
    last_seen: Optional[str] = None
    note_path: Optional[str] = None
    degree: Optional[int] = None
    pagerank: Optional[float] = None
    betweenness: Optional[float] = None
    community: Optional[str] = None
    properties: dict[str, Any] = Field(default_factory=dict)


class SubgraphResponse(BaseModel):
    """Response payload for subgraph queries."""
    model_config = ConfigDict(extra="allow")

    nodes: list[Node]
    edges: list[Edge]
    case_id: Optional[str] = None
    center: Optional[str] = None
    depth: Optional[int] = None


class CertificateRequest(BaseModel):
    """Request payload for generating a BSA §63 certificate."""
    model_config = ConfigDict(extra="allow")

    case_id: str
    subgraph_nodes: list[str] = Field(default_factory=list)
    subgraph_edges: list[str] = Field(default_factory=list)
    officer_name: str = "IO Rajesh Kumar"
    officer_badge: Optional[str] = None
    notes: Optional[str] = None


class ResolveDecision(BaseModel):
    """
    Logged entity resolution decision. Reversible per Law 1.
    """
    model_config = ConfigDict(extra="allow")

    id: Optional[int] = None
    left_id: str
    right_id: str
    block_key: str
    phonetic_score: float
    vector_score: float = 0.0
    context_score: float = 0.0
    combined: float
    decision: str  # auto_merge | auto_reject | pending | human_merge | human_reject | needs_review
    decided_by: str = "system"
    decided_at: Optional[str] = None
    reason: Optional[str] = None
    derivation_chain: Optional[str] = None
    reverted_at: Optional[str] = None


class AgentCard(BaseModel):
    """Frontmatter + content card generated by Cartographer / AI agents."""
    model_config = ConfigDict(extra="allow")

    entity_id: str
    type: str = "suspect"  # suspect | organisation | phone | vehicle | location | event | hypothesis
    canonical_name: str
    aliases: list[str] = Field(default_factory=list)
    thana: Optional[str] = None
    status: str = "active"  # active | arrested | absconding | cleared
    risk_flags: list[str] = Field(default_factory=list)
    communities: list[str] = Field(default_factory=list)
    degree: Optional[int] = None
    pagerank: Optional[float] = None
    betweenness: Optional[float] = None
    first_seen: Optional[str] = None
    last_seen: Optional[str] = None
    summary: Optional[str] = None
    markdown: Optional[str] = None
    sources: list[str] = Field(default_factory=list)
    model: str = "qwen3.5:9b-instruct-q4_K_M"
    generated_at: Optional[str] = None
    human_edited: bool = False


class TreeNode(BaseModel):
    """File tree node for vault explorer UI."""
    model_config = ConfigDict(extra="allow")

    name: str
    displayName: str
    path: str
    isFolder: bool
    children: list["TreeNode"] = Field(default_factory=list)
    is_locked: Optional[bool] = None


class CentralityItem(BaseModel):
    """Centrality ranking item for analytics."""
    model_config = ConfigDict(extra="allow")

    id: str
    name: str
    type: str
    degree: int
    betweenness: float
    pagerank: float


class CertificateResponse(BaseModel):
    """Response payload for generated BSA §63 certificate."""
    model_config = ConfigDict(extra="allow")

    pdf_path: str
    sha256: str
    status: str = "generated"
    case_id: str
    elements_certified: int
    refused_elements: list[str] = Field(default_factory=list)


class VaultIntegrityResponse(BaseModel):
    """Vault integrity status for evidence verification."""
    model_config = ConfigDict(extra="allow")

    status: str = "verified"  # verified | contaminated
    failures: list[str] = Field(default_factory=list)
    document_count: int = 5
